# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Install all libraries"
  lane :setup do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "SwiftHub.xcworkspace", scheme: "SwiftHubUITests")
  end

  lane :beta do
    build_app(scheme: "SwiftHub")
  end

  lane :increment_build do
    increment_build_number
    commit_version_bump
  end

  lane :increment_version_patch do
    increment_version_number(
      bump_type: "patch"
    )
    commit_version_bump
  end

  lane :increment_version_minor do
    increment_version_number(
      bump_type: "minor"
    )
    commit_version_bump
  end

  lane :increment_version_major do
    increment_version_number(
      bump_type: "major"
    )
    commit_version_bump
  end
end
